### ISSUE TITLE
Remove all unnecessary JavaScript and use PHP instead of it

### ISSUE THREAD

**Issue by webprogrammierer** [amzn/amazon-pay-sdk-samples#10]
Your example code uses a lot of JavaScript / JQuery code and shows result data in JSON format, but this is not practical.

Is it possible to remove all unnecessary JavaScript and JQuery code and use PHP instead? 
How?

**Comment by bjguillot** [comment]
Thanks for the suggestion.  I'll discuss with the Amazon Pay SDK team.

Can you expand on why the jQuery and JSON format isn't practical for your implementation?

**Comment by webprogrammierer** [comment]
JSON and a lot of JQuery code (except the calls for Amazon Pay widgets) are not needed for the PHP implementation of Amazon Pay solution.

If we are using PHP we can use PHP also for the error handling and much more. 

We don't need to show the JSON results in browser. No customer will want to see it, this is just a show.

What we need is error handling code in PHP and sending emails to the shop webmaster if errors occur and saving result/errors of every payment to database or text files.

All this can be done better with php!

**Comment by bjguillot** [comment]
I updated the PHP samples recently to clean them up.  I removed references to JavaScript libraries that were not being used in the examples.

I left the code in that shows the JSON results on-screen, as these are intended to be tutorials on how the Amazon Pay API and SDKs work.

Based on your comments, it sounds like what you are looking for is more akin to a "reference implementation" of the PHP SDK that is buyer-facing rather than developer-facing.  That is a good idea and we are thinking about it.
